version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
      TZ: "/usr/share/zoneinfo/America/Argentina/Buenos_Aires"
    paralelism: 2
    steps:
      - add_ssh_keys:
          fingerprints:
          - "72:6d:5a:4f:9c:d4:81:10:b5:1e:99:cb:da:8e:4a:6a"
      - run: git config --global user.email "bot@uqbar.com"
      - run: git config --global user.name "UqbarLandingCI"
      - checkout
      - run:
          command: npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
      - run:
          name: Install yarn
          command: npm install yarn

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            # Yarn cache if available
            - yarn-packages-{{checksum "yarn.lock"}}
      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Publishing
          command: yarn run deploy-ci

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master