version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
      only:
        - master
    docker:
      - image: circleci/node:15.4.0
    environment:
      TZ: "/usr/share/zoneinfo/America/Argentina/Buenos_Aires"
    paralelism: 2
    steps:
      - add_ssh_keys:
          fingerprints:
          - "fe:7b:ef:cc:fd:dc:10:3d:4d:6c:fd:3d:cc:13:ad:89"
      - run: git config --global user.email "bot@uqbar.com"
      - run: git config --global user.name "UqbarLandingCI"
      - run: 
          name: "Setup CI environment variable"
          command: |
            echo 'export CI="false"' >> $BASH_ENV
      - checkout
      - run:
          command: npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
      - run:
          name: Install yarn
          command: npm install yarn

      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Publishing
          command: yarn run deploy
